### ISSUE TITLE
PowerShell Version Requirement

### ISSUE THREAD

**Issue by SPMatthewMcD** [strawgate/ConvertFrom-JsonFast#5]
I stumbled on this when I realized that 80% of the processing time and 100% of the memory use in my module was ConvertFrom-JSON. 

Is there a reason this only works in PowerShell 7+?

**Comment by strawgate** [comment]
This uses System.Text.Json which is a .NET Core 3/4/5 feature. Windows Powershell is based on old .NET Framework and thus will not be available in Windows Powershell.

Depending on what you're doing you may be able to shell out to powershell core to do the json conversion, process the data and pass the processed data to your Windows Powershell session.

You can also import a Windows Powershell session into PowerShell Core and if you need native Windows Powershell cmdlets you could then call them from the session within PowerShell Core.

A very different alternative if you're making web requests you could use invoke-webrequest and save directly to a file and then use a cli tool like `jq` to pluck out the json objects you need.

**Comment by SPMatthewMcD** [comment]
Thanks, I think I'll optimize the code I have and create a release for PowerShell 5 with a note on performance. Using PowerShell 7 and your converter gives me a 5x improvement in performance.
